name: "model_ensemble"
backend: "python"

input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 5, 393 ]
  }
]

output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

instance_group [{ kind: KIND_CPU }]